### POST request to create a new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "BBBBBBBBBBBBBBBBBBBBB",
  "email": "BBBBBBBBBBBBBBBB@example.com",
  "address": "123 hihiBBBBBBBBBBBAAAAA",
  "dateOfBirth": "1999-12-26",
  "registeredDate": "2026-07-03"
}

