spring.application.name=patient-service

# Uncomment to use the in-memory database outside of docker
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#
#spring.datasource.username=admin
#spring.datasource.password=password
#
## tells spring to update the db for any change in our entities
#spring.jpa.hibernate.ddl-auto=update
##spring.jpa.open-in-view=false
#
## this makes it so that it checks against the db/entities at every start
#spring.sql.init.mode=always

spring.kafka.bootstrap-servers=kafka:9092

# telling spring-kafka code that our messages wil have a key of String and a value of ByteArray
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

server.port=4000
logging.level.root=info